### ISSUE TITLE
Sharing Spaces

### ISSUE THREAD

**Issue by jak266** [Zefalcon/ATSSG#1]
The AI acts like you can share spaces, but the rest of the code doesn't support it.

**Comment by jak266** [comment]
When a unit dies, the AI still tries to execute actions on it, both attacking it or using it.

**Comment by jak266** [comment]
Entities shouldn't be in both players and the GameMap. The code that needs entities in GameMap should access them through the player instead.

**Comment by Turtlelord26** [comment]
We've added functional multiple-occupancy.
