### ISSUE TITLE
Flagged hack: UnitType.Soldier

### ISSUE THREAD

**Issue by Turtlelord26** [Zefalcon/ATSSG#16]
Flag on the instakill damage numbers written expressly to speed up the demo. Incidentally why are the range and damage part of the UnitType and not the AttackType?

**Comment by TomShkurti** [comment]
I think we can just move the "real soldier" into soldier when we update the units; there's little need for the hacked soldier any more.

**Comment by Turtlelord26** [comment]
Naturally. The question still stands though: if range and damage are intrinsic to units what do we even do with the AttackType enum?

**Comment by TomShkurti** [comment]
Closing as attack type may be left or purged in the dead-code crush, but is otherwise finalized.
