### ISSUE TITLE
Flags in Cell

### ISSUE THREAD

**Issue by Turtlelord26** [Zefalcon/ATSSG#19]
Potential aberrant behavior in Cell.addActionListener: currently is not protected from Cells receiving multiple listeners. I can't see how it would ever happen, but we should probably protect it anyway.

Flag in Cell.updateView: proposes new conditional structure and art design, specifically one or a class of "army" icon that cells would use when multiply-occupied.

**Comment by Turtlelord26** [comment]
ActionListener flag purged.

Art flag remains.

a flag in removeEntity: assumes single-occupancy

**Comment by TomShkurti** [comment]
Regarding the art flag, I am thinking a picture of the topmost unit works well enough... possibly make a "stack" border?

**Comment by Turtlelord26** [comment]
Bookkeeping: removeEntity flag was dealt with some time ago.

I don't think using the border to indicate stacking will work as I was planning to use that space to indicate the current selection.

**Comment by TomShkurti** [comment]
Hmm, I was thinking something like this:

![image](https://cloud.githubusercontent.com/assets/2729363/20730190/1cffa10a-b653-11e6-84e6-27df225f7feb.png)
Single occupancy

![image](https://cloud.githubusercontent.com/assets/2729363/20730221/36094886-b653-11e6-9f24-7bb0e6ee22e2.png)
Multiple occupancy

The image would be made smaller and given the 'stack' edges, but we would still only use the one.

**Comment by TomShkurti** [comment]
Anything further to resolve here?

**Comment by jak266** [comment]
Not that I know of.

**Comment by Turtlelord26** [comment]
Cell is devoid of flags.
