### ISSUE TITLE
Flag on Entity

### ISSUE THREAD

**Issue by Turtlelord26** [Zefalcon/ATSSG#22]
The question was raised of whether allowedCommands should continue to be a Collection or should instead be a concrete type.

**Comment by TomShkurti** [comment]
I see no reason not to do so.

**Comment by jak266** [comment]
Why would we make it a concrete type? Having it as a list has to be somewhere, so it might as well be in Entity.

**Comment by TomShkurti** [comment]
Changing to List does not seem to have broken anything.

**Comment by Turtlelord26** [comment]
There was that bit in class awhile back about 'programming to interfaces'
