### ISSUE TITLE
Flag on Unit

### ISSUE THREAD

**Issue by Turtlelord26** [Zefalcon/ATSSG#23]
Propose moving the allowedCommands field away from Entity altogether and instead defining it in the UnitType and BuildingType enums.

**Comment by TomShkurti** [comment]
Pretty sure all units have the same set of them, and there's no reason that would change.

**Comment by jak266** [comment]
It would be repetitive code to redefine it for every Unit. If we have a feature that needs different commands for units, but not subclasses then we can change it. I'm closing the issue because any new feature should be in a new issue.

**Comment by TomShkurti** [comment]
Removing the flag as well then.
