### ISSUE TITLE
*Serious* New Game Hang

### ISSUE THREAD

**Issue by Turtlelord26** [Zefalcon/ATSSG#30]
Starting a new game then starting another new game (same or different scenario) and then ending the turn causes a fatal hang with high processor activity.

**Comment by Turtlelord26** [comment]
Fixed it, see commit 111

**Comment by Turtlelord26** [comment]
Bug somehow reintroduced by GUIR. I managed to partially fix it in the latest commit (114). It is now in the state where ending the turn never calls AI's execute, probably due to a pointer mishandling.

**Comment by Turtlelord26** [comment]
Squashed again, hopefully forever.

**Comment by TomShkurti** [comment]
Do you know if/when I will be able to see the whole game screen again?

**Comment by Turtlelord26** [comment]
If you are referring to the wierdness where you were seeing all of Large.map, zoom functionality is on my section of the priorities list, though at it's current ordering it's a coin flip whether it makes it into the demo Monday.

**Comment by TomShkurti** [comment]
I was referring to the fact that on my computer, I cannot see any of the
turn or action buttons- the game map takes up the whole screen.
