### ISSUE TITLE
Make the terrain even more awesome.

### ISSUE THREAD

**Issue by TomShkurti** [Zefalcon/ATSSG#38]
Possibly using Pokemon tile sets.

**Comment by Turtlelord26** [comment]
My best idea for implementing multiple images for each terrain involves using multiple terraintypes (e.g. grass, grass2, grass3) and having the load system randomly assign one of these grasses when it encounters 'g'. Is that feasible given your current mapping system?

**Comment by Zefalcon** [comment]
It'd be more tedious for passable terrain, then.

**Comment by jak266** [comment]
I'll edit terrain to take a list of image locations and return a random one.

**Comment by jak266** [comment]
Just submitted a change that does that.

**Comment by jak266** [comment]
Detail card will need to be changed to tell which image the cell it's on is using.

**Comment by Turtlelord26** [comment]
It required changes in MainMap, EntityCard, and DetailCard but this will supported functionality on my next commit.

**Comment by TomShkurti** [comment]
New terrain textures are up.

**Comment by Turtlelord26** [comment]
aaaand implemented!
The grass and rocks look really smooth, can't reliably tell where cells end anymore.

**Comment by TomShkurti** [comment]
Does the blank minimap actually show up or do anything?

**Comment by jak266** [comment]
I see a full minimap.

**Comment by Turtlelord26** [comment]
No it doesn't do anything. It's purely informational for now.

**Comment by Turtlelord26** [comment]
Now it has clickyness too.

**Comment by TomShkurti** [comment]
What are we still looking at in terms of art?

**Comment by Turtlelord26** [comment]
I could use an icon for a stats button.
I am thinking it would be a button (technically, a label) that I would put in the bottom of the commandCard that when hovered would display relevant unit stats like movespeed, range, and damage.
Base image should be the same size as the other commands (e.g. idle), I don't have a suggestion for how it should look.

**Comment by Turtlelord26** [comment]
Oh, and if you could send an image like that rolled out scroll map except rolled up that could see use.
And if you want to make a custom error icon for trying to end the turn without ordering units edit DemoPromptError.

**Comment by TomShkurti** [comment]
Oh, is that actually used?

I'll try to get these done before we meet.

**Comment by TomShkurti** [comment]
What should I call it?
