### ISSUE TITLE
End Turn Automation

### ISSUE THREAD

**Issue by Turtlelord26** [Zefalcon/ATSSG#4]
Currently there is no support for ending turns in automated testing.
Proposition: a protected clicker method in EndTurnButton

**Comment by Zefalcon** [comment]
Has this been done?

**Comment by Turtlelord26** [comment]
No. Do we need/want it?

**Comment by jak266** [comment]
Not for Friday

**Comment by Turtlelord26** [comment]
Being clear, it's literally a 2-second change in EndTurnButton. Time costs would come from incorporating it into tests.

**Comment by jak266** [comment]
Then add the handle. Whether we use it or not is flexible.

**Comment by TomShkurti** [comment]
Did this just happen?

**Comment by Turtlelord26** [comment]
Yes
