### ISSUE TITLE
Unit Queue

### ISSUE THREAD

**Issue by Turtlelord26** [Zefalcon/ATSSG#48]
Do we still want it to happen?
(Relevant information: I don't think it'll be hard unless it somehow needs a connection to the scripting classes that is stronger than boolean doesUnitHaveScript)

**Comment by jak266** [comment]
I don't think we should add anything new at this point

**Comment by TomShkurti** [comment]
I concur, especially since I still need to test the scrip saving once scripts are sticking.

**Comment by Turtlelord26** [comment]
Almost
