### ISSUE TITLE
Illegal Order Notification

### ISSUE THREAD

**Issue by Turtlelord26** [Zefalcon/ATSSG#7]
Attempting to assign a unit an order it cannot complete should instead assign no order (implemented) and generate a prompt detailing the error (not implemented).

**Comment by Turtlelord26** [comment]
Current implementation still assigns illegal orders but never executes them. To properly implement the Unit Queue and error messages on illegal orders I need the action of assigning the order to check legality and be able to pass that information back as a return, so that trying to assign a unit an illegal order leaves its order field blank and my code knows that happened.

If you have time I would prefer someone who knows the inner workings of actions and entities already make these adjustments.

**Comment by jak266** [comment]
What exactly do you want? I can check if it is one of the allowed command types. Or do you mean that you want me to predict if it can execute or not?

**Comment by jak266** [comment]
Take a look at my latest commit and see if it does what you need

**Comment by Turtlelord26** [comment]
This is precisely what I had in mind, though ideally we can enable more specific error information sometime.

**Comment by jak266** [comment]
If there is something specific you want, let me know. Currently I'm just calling the validation method that returns a boolean in execute.

**Comment by Turtlelord26** [comment]
AttackAction should only ever fail when the enemy is too far away, since the control flow stops in MainMap if the attack click doesn't hit an enemy (I made a prompt handling that case). Maybe include range data in the error message (e.g. That enemy is X units away and this unit's range is Y)? If that's feasible then it would be good to have in MoveAction too (attempted range of move vs actual range).

By the way, how does scripting feel about this structural change in the actions?

**Comment by jak266** [comment]
Returning that information would mean restructuring part of the program. It currently is designed to only return  a boolean. Also, something can be a illegal move if it costs too much, but still be within the technical move range.

**Comment by Turtlelord26** [comment]
I don't know about Move then, but at least for attack could we include range data by adding it to the RuntimeException string?

**Comment by jak266** [comment]
I duplicated some code. Feel free to edit the string literal partsof the statement if you want to phrase it differently
